In [1]:
!redsea \
  /mnt/jwh83-data/Confetti/data/CODEX/new/done/B004-A-304.tif \
  /mnt/jwh83-data/Confetti/output/intestine_data_mask_outputs/CellSAM_3_20260113_TIF/B004-A-304_rgb_cellSAM.tif \
  /mnt/jwh83-data/Confetti/data/CODEX/ns_mp_codex_channel_list.csv \
  /mnt/jwh83-data/Confetti/output/Redsea/20260127_ns444_CellSAM/B004-A-304 \
  --element-shape star \
  --element-size 2

MainProcess 2026-01-27 15:19:45,760 INFO: Reading image
MainProcess 2026-01-27 15:20:25,559 INFO: Reading segmentation mask
MainProcess 2026-01-27 16:01:54,585 INFO: Quantifying markers before correction
MainProcess 2026-01-27 16:02:00,147 INFO: Creating cell-cell contact matrix
MainProcess 2026-01-27 16:05:51,474 INFO: Performing correction
Progress: |██████████████████████████████████████████████████| 100.0% Complete
MainProcess 2026-01-27 16:44:27,960 INFO: Writing output files to /mnt/jwh83-data/Confetti/output/Redsea/20260127_ns444_CellSAM/B004-A-304
MainProcess 2026-01-27 16:44:29,616 INFO: Done

In [2]:
!redsea \
  /mnt/jwh83-data/Confetti/data/CODEX/new/done/B004-A-004.tif \
  /mnt/jwh83-data/Confetti/output/intestine_data_mask_outputs/CellSAM_3_20260113_TIF/B004-A-004_rgb_cellSAM.tif \
  /mnt/jwh83-data/Confetti/data/CODEX/ns_mp_codex_channel_list.csv \
  /mnt/jwh83-data/Confetti/output/Redsea/20260127_ns444_CellSAM/B004-A-004 \
  --element-shape star \
  --element-size 2

MainProcess 2026-01-27 16:44:30,146 INFO: Reading image
MainProcess 2026-01-27 16:45:12,388 INFO: Reading segmentation mask
MainProcess 2026-01-27 17:30:46,803 INFO: Quantifying markers before correction
MainProcess 2026-01-27 17:30:52,768 INFO: Creating cell-cell contact matrix
MainProcess 2026-01-27 17:34:41,158 INFO: Performing correction
Progress: |██████████████████████████████████████████████████| 100.0% Complete
MainProcess 2026-01-27 18:12:18,365 INFO: Writing output files to /mnt/jwh83-data/Confetti/output/Redsea/20260127_ns444_CellSAM/B004-A-004
MainProcess 2026-01-27 18:12:20,026 INFO: Done

In [3]:
!redsea \
  /mnt/jwh83-data/Confetti/data/CODEX/new/done/B004-A-008.tif \
  /mnt/jwh83-data/Confetti/output/intestine_data_mask_outputs/CellSAM_3_20260113_TIF/B004-A-008_rgb_cellSAM.tif \
  /mnt/jwh83-data/Confetti/data/CODEX/ns_mp_codex_channel_list.csv \
  /mnt/jwh83-data/Confetti/output/Redsea/20260127_ns444_CellSAM/B004-A-008 \
  --element-shape star \
  --element-size 2

MainProcess 2026-01-27 18:12:20,570 INFO: Reading image
MainProcess 2026-01-27 18:13:00,658 INFO: Reading segmentation mask
MainProcess 2026-01-27 19:04:01,155 INFO: Quantifying markers before correction
MainProcess 2026-01-27 19:04:08,079 INFO: Creating cell-cell contact matrix
MainProcess 2026-01-27 19:08:02,000 INFO: Performing correction
Progress: |██████████████████████████████████████████████████| 100.0% Complete
MainProcess 2026-01-27 20:08:30,326 INFO: Writing output files to /mnt/jwh83-data/Confetti/output/Redsea/20260127_ns444_CellSAM/B004-A-008
MainProcess 2026-01-27 20:08:33,145 INFO: Done

In [4]:
!redsea \
  /mnt/jwh83-data/Confetti/data/CODEX/new/done/B004-A-104.tif \
  /mnt/jwh83-data/Confetti/output/intestine_data_mask_outputs/CellSAM_3_20260113_TIF/B004-A-104_rgb_cellSAM.tif \
  /mnt/jwh83-data/Confetti/data/CODEX/ns_mp_codex_channel_list.csv \
  /mnt/jwh83-data/Confetti/output/Redsea/20260127_ns444_CellSAM/B004-A-104 \
  --element-shape star \
  --element-size 2

MainProcess 2026-01-27 20:08:33,669 INFO: Reading image
MainProcess 2026-01-27 20:09:46,542 INFO: Reading segmentation mask
MainProcess 2026-01-27 21:13:06,491 INFO: Quantifying markers before correction
MainProcess 2026-01-27 21:13:15,219 INFO: Creating cell-cell contact matrix
MainProcess 2026-01-27 21:17:06,108 INFO: Performing correction
Progress: |██████████████████████████████████████████████████| 100.0% Complete
MainProcess 2026-01-27 22:29:34,005 INFO: Writing output files to /mnt/jwh83-data/Confetti/output/Redsea/20260127_ns444_CellSAM/B004-A-104
MainProcess 2026-01-27 22:29:38,441 INFO: Done

In [5]:
!redsea \
  /mnt/jwh83-data/Confetti/data/CODEX/new/done/B004-A-204.tif \
  /mnt/jwh83-data/Confetti/output/intestine_data_mask_outputs/CellSAM_3_20260113_TIF/B004-A-204_rgb_cellSAM.tif \
  /mnt/jwh83-data/Confetti/data/CODEX/ns_mp_codex_channel_list.csv \
  /mnt/jwh83-data/Confetti/output/Redsea/20260127_ns444_CellSAM/B004-A-204 \
  --element-shape star \
  --element-size 2

MainProcess 2026-01-27 22:29:38,976 INFO: Reading image
MainProcess 2026-01-27 22:30:23,214 INFO: Reading segmentation mask
MainProcess 2026-01-27 23:06:04,342 INFO: Quantifying markers before correction
MainProcess 2026-01-27 23:06:09,240 INFO: Creating cell-cell contact matrix
MainProcess 2026-01-27 23:10:03,252 INFO: Performing correction
Progress: |██████████████████████████████████████████████████| 100.0% Complete
MainProcess 2026-01-27 23:51:08,874 INFO: Writing output files to /mnt/jwh83-data/Confetti/output/Redsea/20260127_ns444_CellSAM/B004-A-204
MainProcess 2026-01-27 23:51:10,695 INFO: Done

In [6]:
!redsea \
  /mnt/jwh83-data/Confetti/data/CODEX/new/done/B004-A-404.tif \
  /mnt/jwh83-data/Confetti/output/intestine_data_mask_outputs/CellSAM_3_20260113_TIF/B004-A-404_rgb_cellSAM.tif \
  /mnt/jwh83-data/Confetti/data/CODEX/ns_mp_codex_channel_list.csv \
  /mnt/jwh83-data/Confetti/output/Redsea/20260127_ns444_CellSAM/B004-A-404 \
  --element-shape star \
  --element-size 2

MainProcess 2026-01-27 23:51:11,218 INFO: Reading image
MainProcess 2026-01-27 23:51:53,549 INFO: Reading segmentation mask
MainProcess 2026-01-28 00:58:23,459 INFO: Quantifying markers before correction
MainProcess 2026-01-28 00:58:31,265 INFO: Creating cell-cell contact matrix
MainProcess 2026-01-28 01:02:24,910 INFO: Performing correction
Progress: |██████████████████████████████████████████████████| 100.0% Complete
Traceback (most recent call last):
  File "/home/labuser/anaconda3/envs/redseapy/bin/redsea", line 7, in <module>
    sys.exit(redsea())
  File "/home/labuser/anaconda3/envs/redseapy/lib/python3.10/site-packages/redseapy/cli.py", line 66, in redsea
    redsea_mod.run_redsea(
  File "/home/labuser/anaconda3/envs/redseapy/lib/python3.10/site-packages/redseapy/redsea.py", line 363, in run_redsea
    d["x_centroid"] = centroid_xs
  File "/home/labuser/anaconda3/envs/redseapy/lib/python3.10/site-packages/pandas/core/frame.py", line 4322, in __setitem__
    self._set_item(key, value)
  File "/home/labuser/anaconda3/envs/redseapy/lib/python3.10/site-packages/pandas/core/frame.py", line 4535, in _set_item
    value, refs = self._sanitize_column(value)
  File "/home/labuser/anaconda3/envs/redseapy/lib/python3.10/site-packages/pandas/core/frame.py", line 5288, in _sanitize_column
    com.require_length_match(value, self.index)
  File "/home/labuser/anaconda3/envs/redseapy/lib/python3.10/site-packages/pandas/core/common.py", line 573, in require_length_match
    raise ValueError(
ValueError: Length of values (29876) does not match length of index (29873)

In [7]:
!redsea \
  /mnt/jwh83-data/Confetti/data/CODEX/new/done/B004-A-408.tif \
  /mnt/jwh83-data/Confetti/output/intestine_data_mask_outputs/CellSAM_3_20260113_TIF/B004-A-408_rgb_cellSAM.tif \
  /mnt/jwh83-data/Confetti/data/CODEX/ns_mp_codex_channel_list.csv \
  /mnt/jwh83-data/Confetti/output/Redsea/20260127_ns444_CellSAM/B004-A-408 \
  --element-shape star \
  --element-size 2

MainProcess 2026-01-28 02:11:09,335 INFO: Reading image
MainProcess 2026-01-28 02:12:05,499 INFO: Reading segmentation mask
MainProcess 2026-01-28 03:00:53,272 INFO: Quantifying markers before correction
MainProcess 2026-01-28 03:01:00,218 INFO: Creating cell-cell contact matrix
MainProcess 2026-01-28 03:04:48,126 INFO: Performing correction
Progress: |██████████████████████████████████████████████████| 100.0% Complete
MainProcess 2026-01-28 03:59:40,371 INFO: Writing output files to /mnt/jwh83-data/Confetti/output/Redsea/20260127_ns444_CellSAM/B004-A-408
MainProcess 2026-01-28 03:59:42,934 INFO: Done

In [9]:
!redsea \
  /mnt/jwh83-data/Confetti/data/CODEX/new/done/B004-A-504.tif \
  /mnt/jwh83-data/Confetti/output/intestine_data_mask_outputs/CellSAM_3_20260113_TIF/B004-A-504_rgb_cellSAM.tif \
  /mnt/jwh83-data/Confetti/data/CODEX/ns_mp_codex_channel_list.csv \
  /mnt/jwh83-data/Confetti/output/Redsea/20260127_ns444_CellSAM/B004-A-504 \
  --element-shape star \
  --element-size 2

MainProcess 2026-01-30 14:56:02,326 INFO: Reading image
MainProcess 2026-01-30 14:56:49,108 INFO: Reading segmentation mask
MainProcess 2026-01-30 16:07:24,924 INFO: Quantifying markers before correction
MainProcess 2026-01-30 16:07:34,672 INFO: Creating cell-cell contact matrix
MainProcess 2026-01-30 16:13:28,496 INFO: Performing correction
Progress: |██████████████████████████████████████████████████| 100.0% Complete
MainProcess 2026-01-30 17:42:20,146 INFO: Writing output files to /mnt/jwh83-data/Confetti/output/Redsea/20260127_ns444_CellSAM/B004-A-504
MainProcess 2026-01-30 17:42:24,037 INFO: Done

In [1]:
!redsea \
  /mnt/jwh83-data/Confetti/data/CODEX/new/done/B004-A-404.tif \
  /mnt/jwh83-data/Confetti/output/intestine_data_mask_outputs/CellSAM_3_20260113_TIF/B004-A-404_cellSAM_label_clean_relabel.tif \
  /mnt/jwh83-data/Confetti/data/CODEX/ns_mp_codex_channel_list.csv \
  /mnt/jwh83-data/Confetti/output/Redsea/20260127_ns444_CellSAM/B004-A-404 \
  --element-shape star \
  --element-size 1

MainProcess 2026-02-01 15:04:17,929 INFO: Reading image
MainProcess 2026-02-01 15:05:00,228 INFO: Reading segmentation mask
MainProcess 2026-02-01 16:11:35,954 INFO: Quantifying markers before correction
MainProcess 2026-02-01 16:11:43,720 INFO: Creating cell-cell contact matrix
MainProcess 2026-02-01 16:15:38,270 INFO: Performing correction
Progress: |██████████████████████████████████████████████████| 100.0% Complete
Traceback (most recent call last):
  File "/home/labuser/anaconda3/envs/redseapy/bin/redsea", line 7, in <module>
    sys.exit(redsea())
  File "/home/labuser/anaconda3/envs/redseapy/lib/python3.10/site-packages/redseapy/cli.py", line 66, in redsea
    redsea_mod.run_redsea(
  File "/home/labuser/anaconda3/envs/redseapy/lib/python3.10/site-packages/redseapy/redsea.py", line 363, in run_redsea
    d["x_centroid"] = centroid_xs
  File "/home/labuser/anaconda3/envs/redseapy/lib/python3.10/site-packages/pandas/core/frame.py", line 4322, in __setitem__
    self._set_item(key, value)
  File "/home/labuser/anaconda3/envs/redseapy/lib/python3.10/site-packages/pandas/core/frame.py", line 4535, in _set_item
    value, refs = self._sanitize_column(value)
  File "/home/labuser/anaconda3/envs/redseapy/lib/python3.10/site-packages/pandas/core/frame.py", line 5288, in _sanitize_column
    com.require_length_match(value, self.index)
  File "/home/labuser/anaconda3/envs/redseapy/lib/python3.10/site-packages/pandas/core/common.py", line 573, in require_length_match
    raise ValueError(
ValueError: Length of values (29847) does not match length of index (29845)

In [6]:
import os, glob, json, math, time
import numpy as np
import pandas as pd

try:
    import tifffile as tiff
except Exception:
    tiff = None

from skimage.measure import regionprops_table
from skimage.measure import label as cc_label

def _stat_file(path):
    d = {"path": path, "exists": os.path.exists(path)}
    if not d["exists"]:
        return d
    st = os.stat(path)
    d.update({
        "size_bytes": int(st.st_size),
        "mtime": time.strftime("%Y-%m-%d %H:%M:%S", time.localtime(st.st_mtime)),
        "readable": os.access(path, os.R_OK),
    })
    return d

def _list_dir_tree(root, max_files=2000):
    if not os.path.exists(root):
        return []
    files = []
    for p in glob.glob(os.path.join(root, "**/*"), recursive=True):
        if os.path.isfile(p):
            files.append(p)
        if len(files) >= max_files:
            break
    return sorted(files)

def _summarize_dir(root):
    files = _list_dir_tree(root)
    exts = pd.Series([os.path.splitext(f)[1].lower() for f in files]).value_counts().to_dict()
    keyfiles = [f for f in files if any(k in os.path.basename(f).lower() for k in ["before", "after", "single", "cell", "log", "error", "trace"])]
    sizes = []
    for f in files:
        try:
            sizes.append(os.stat(f).st_size)
        except Exception:
            pass
    return {
        "outdir": root,
        "n_files": len(files),
        "ext_counts": exts,
        "total_bytes": int(sum(sizes)) if sizes else 0,
        "keyfiles_sample": keyfiles[:30],
        "all_files_sample": files[:30],
    }

def _read_tiff_meta(path, max_pages_for_sampling=1):
    out = {"path": path, "ok": False}
    if tiff is None:
        out["error"] = "tifffile not installed"
        return out
    if not os.path.exists(path):
        out["error"] = "missing"
        return out
    try:
        with tiff.TiffFile(path) as tf:
            out["ok"] = True
            out["n_pages"] = len(tf.pages)
            out["is_ome"] = bool(tf.is_ome)
            out["series_count"] = len(tf.series)
            s0 = tf.series[0]
            out["series0_shape"] = tuple(s0.shape)
            out["series0_dtype"] = str(s0.dtype)
            out["series0_axes"] = getattr(s0, "axes", None)
            p0 = tf.pages[0]
            out["page0_shape"] = tuple(getattr(p0, "shape", ()))
            out["page0_dtype"] = str(getattr(p0, "dtype", ""))
            out["page0_compression"] = str(getattr(p0, "compression", ""))
            out["page0_photometric"] = str(getattr(p0, "photometric", ""))
            out["page0_planarconfig"] = str(getattr(p0, "planarconfig", ""))
            out["page0_is_tiled"] = bool(getattr(p0, "is_tiled", False))
            if out["page0_is_tiled"]:
                out["page0_tilewidth"] = int(getattr(p0, "tilewidth", 0) or 0)
                out["page0_tilelength"] = int(getattr(p0, "tilelength", 0) or 0)
            else:
                out["page0_rowsperstrip"] = int(getattr(p0, "rowsperstrip", 0) or 0)

            ome = None
            if tf.is_ome:
                try:
                    ome = tf.ome_metadata
                except Exception:
                    ome = None
            out["ome_metadata_present"] = ome is not None
    except Exception as e:
        out["error"] = repr(e)
    return out

def _read_mask(path):
    if tiff is None:
        raise ImportError("tifffile not installed")
    arr = tiff.imread(path)
    if arr.ndim == 3 and arr.shape[-1] in (3,4):
        raise ValueError(f"Mask looks RGB/RGBA (shape={arr.shape}). Expected integer label image.")
    return arr

def _mask_stats(mask, small_area=10, comp_check_n=50):
    mask_int = mask.astype(np.int64, copy=False)
    uniq = np.unique(mask_int)
    labels = uniq[uniq != 0]
    props = regionprops_table(mask_int, properties=("label","area","bbox","centroid"))
    df = pd.DataFrame(props).rename(columns={"centroid-0":"y_centroid","centroid-1":"x_centroid"})
    df = df.sort_values("label").reset_index(drop=True)
    tiny = df[df["area"] < small_area]
    h,w = mask_int.shape[:2]
    border = df[
        (df["bbox-0"] == 0) |
        (df["bbox-1"] == 0) |
        (df["bbox-2"] == h) |
        (df["bbox-3"] == w)
    ]
    has_non_integer = False
    if np.issubdtype(mask.dtype, np.floating):
        has_non_integer = not np.all(np.isclose(mask, np.round(mask)))
    maxv = int(uniq.max()) if uniq.size else 0
    contiguous = False
    missing_count = None
    if labels.size and maxv <= 10_000_000:
        expected = np.arange(1, maxv+1, dtype=np.int64)
        missing_count = int(np.setdiff1d(expected, labels).size)
        contiguous = (missing_count == 0 and maxv == labels.size)
    smallest = df.nsmallest(min(comp_check_n, len(df)), "area")["label"].to_list() if len(df) else []
    multi = []
    for lab in smallest:
        binary = (mask_int == lab)
        if not np.any(binary):
            continue
        cc = cc_label(binary, connectivity=1)
        if int(cc.max()) > 1:
            multi.append((int(lab), int(cc.max())))
    return {
        "shape": tuple(mask_int.shape),
        "dtype": str(mask.dtype),
        "min": int(uniq.min()) if uniq.size else 0,
        "max": int(uniq.max()) if uniq.size else 0,
        "unique_incl_0": int(uniq.size),
        "labels_excl_0": int(labels.size),
        "centroid_rows": int(df.shape[0]),
        "label_min": int(df["label"].min()) if len(df) else None,
        "label_max": int(df["label"].max()) if len(df) else None,
        "nonzero_pixels": int(np.count_nonzero(mask_int)),
        "has_negative": bool(np.any(uniq < 0)),
        "has_non_integer": bool(has_non_integer),
        "contiguous_1_to_n": bool(contiguous),
        "missing_in_1_to_max": missing_count,
        "tiny_n": int(tiny.shape[0]),
        "tiny_labels_head": tiny["label"].head(30).astype(int).tolist(),
        "border_touch_n": int(border.shape[0]),
        "border_touch_labels_head": border["label"].head(30).astype(int).tolist(),
        "multi_component_smallest_n": len(multi),
        "multi_component_examples": multi[:30],
        "area_summary": {
            "p0": float(df["area"].min()) if len(df) else None,
            "p1": float(np.quantile(df["area"], 0.01)) if len(df) else None,
            "p5": float(np.quantile(df["area"], 0.05)) if len(df) else None,
            "p50": float(np.quantile(df["area"], 0.50)) if len(df) else None,
            "p95": float(np.quantile(df["area"], 0.95)) if len(df) else None,
            "p99": float(np.quantile(df["area"], 0.99)) if len(df) else None,
            "max": float(df["area"].max()) if len(df) else None,
            "mean": float(df["area"].mean()) if len(df) else None,
        },
        "labels_set_sample": df["label"].head(10).astype(int).tolist() + (df["label"].tail(10).astype(int).tolist() if len(df) else []),
    }, df

def _read_image_sampled(path, max_pixels=2_000_000):
    if tiff is None:
        raise ImportError("tifffile not installed")
    with tiff.TiffFile(path) as tf:
        arr = tf.series[0].asarray()
    a = np.asarray(arr)
    shape = a.shape
    dtype = str(a.dtype)

    # Normalize to (..., Y, X) where possible, keeping leading dims as "planes"
    if a.ndim == 2:
        planes = 1
        yx = a.shape
        a2 = a[None, ...]
    else:
        yx = a.shape[-2:]
        planes = int(np.prod(a.shape[:-2]))
        a2 = a.reshape((planes, yx[0], yx[1]))

    y, x = yx
    npx = y * x
    step = max(1, int(math.floor(math.sqrt(npx / max_pixels)))) if npx > max_pixels else 1
    samp = a2[:, ::step, ::step]

    samp_f = samp.astype(np.float32, copy=False)
    finite = np.isfinite(samp_f)
    nan_n = int(np.isnan(samp_f).sum())
    inf_n = int(np.isinf(samp_f).sum())

    per_plane = []
    for i in range(min(planes, 128)):
        v = samp_f[i]
        fin = finite[i]
        if fin.any():
            vv = v[fin]
            per_plane.append({
                "plane": i,
                "min": float(vv.min()),
                "max": float(vv.max()),
                "mean": float(vv.mean()),
                "std": float(vv.std()),
                "finite_frac": float(fin.mean()),
                "is_constant": bool(vv.min() == vv.max()),
                "is_all_zero": bool(vv.min() == 0 and vv.max() == 0),
            })
        else:
            per_plane.append({
                "plane": i,
                "min": None, "max": None, "mean": None, "std": None,
                "finite_frac": 0.0, "is_constant": True, "is_all_zero": False
            })
    per_plane_df = pd.DataFrame(per_plane)

    return {
        "shape": tuple(shape),
        "dtype": dtype,
        "planes_inferred": planes,
        "yx": tuple(yx),
        "sampling_step": int(step),
        "nan_n_sample": nan_n,
        "inf_n_sample": inf_n,
        "any_nan_sample": bool(nan_n > 0),
        "any_inf_sample": bool(inf_n > 0),
        "constant_planes_n_first128": int(per_plane_df["is_constant"].sum()),
        "allzero_planes_n_first128": int(per_plane_df["is_all_zero"].sum()),
        "per_plane_df_first128": per_plane_df,
    }

def _image_mask_compat(image_info, mask_info):
    iy, ix = image_info["yx"]
    my, mx = mask_info["shape"][:2]
    return {
        "image_yx": (iy, ix),
        "mask_yx": (my, mx),
        "same_xy": bool((iy, ix) == (my, mx)),
        "delta_y": int(my - iy),
        "delta_x": int(mx - ix),
    }

def _read_channel_list(csv_path):
    if not os.path.exists(csv_path):
        return {"path": csv_path, "exists": False}
    try:
        df = pd.read_csv(csv_path)
    except Exception:
        df = pd.read_csv(csv_path, sep="\t")
    return {
        "path": csv_path,
        "exists": True,
        "rows": int(df.shape[0]),
        "cols": int(df.shape[1]),
        "head": df.head(10),
        "colnames": list(df.columns),
    }

def analyze_case(name, image_path, mask_path, channel_csv, outdir):
    out = {"name": name}

    out["files"] = pd.DataFrame([
        _stat_file(image_path),
        _stat_file(mask_path),
        _stat_file(channel_csv),
        _stat_file(outdir),
    ])

    out["image_tiff_meta"] = _read_tiff_meta(image_path)
    out["mask_tiff_meta"] = _read_tiff_meta(mask_path)

    mask = _read_mask(mask_path)
    mstats, mprops = _mask_stats(mask)
    out["mask_stats"] = mstats
    out["mask_props_df"] = mprops

    img = _read_image_sampled(image_path)
    out["image_stats"] = {k:v for k,v in img.items() if k != "per_plane_df_first128"}
    out["image_plane_df"] = img["per_plane_df_first128"]

    out["compat"] = _image_mask_compat(img, mstats)

    out["channels"] = _read_channel_list(channel_csv)

    out["outdir_summary"] = _summarize_dir(outdir)

    logs = []
    for f in _list_dir_tree(outdir):
        bn = os.path.basename(f).lower()
        if any(k in bn for k in ["log", "stderr", "stdout", "trace", "error"]):
            logs.append(f)
    out["log_files"] = logs[:50]

    log_hits = []
    for lf in out["log_files"][:10]:
        try:
            with open(lf, "r", errors="ignore") as fh:
                txt = fh.read()
            for key in ["traceback", "valueerror", "exception", "killed", "memoryerror", "nan", "inf", "failed"]:
                if key in txt.lower():
                    log_hits.append((lf, key))
        except Exception:
            pass
    out["log_hits"] = log_hits

    return out

def show_case(case):
    print(f"\n==================== {case['name']} ====================")
    display(case["files"])
    print("\nTIFF META (image):"); print(json.dumps(case["image_tiff_meta"], indent=2, default=str)[:2000])
    print("\nTIFF META (mask):");  print(json.dumps(case["mask_tiff_meta"], indent=2, default=str)[:2000])
    print("\nMASK STATS:");        print(json.dumps(case["mask_stats"], indent=2, default=str)[:2000])
    print("\nIMAGE STATS:");       print(json.dumps(case["image_stats"], indent=2, default=str)[:2000])
    print("\nIMAGE↔MASK COMPAT:"); print(json.dumps(case["compat"], indent=2, default=str))
    print("\nCHANNEL LIST:"); 
    if case["channels"].get("exists"):
        print({k:case["channels"][k] for k in ["path","rows","cols"]})
        display(case["channels"]["head"])
    else:
        print(case["channels"])
    print("\nOUTDIR SUMMARY:");    print(json.dumps(case["outdir_summary"], indent=2, default=str)[:2500])
    if case["log_files"]:
        print("\nLOG FILES (sample):")
        for f in case["log_files"][:15]:
            print(" ", f)
        if case["log_hits"]:
            print("\nLOG HITS:")
            for lf,key in case["log_hits"]:
                print(" ", key, "->", lf)

def diff_cases(a, b):
    def flatten(prefix, obj, out):
        if isinstance(obj, dict):
            for k,v in obj.items():
                flatten(prefix + [k], v, out)
        elif isinstance(obj, (list, tuple)):
            if len(obj) and all(isinstance(x,(int,float,str,bool,type(None))) for x in obj[:20]):
                out["/".join(prefix)] = str(obj[:20])
            else:
                out["/".join(prefix)] = f"<list len={len(obj)}>"
        else:
            out["/".join(prefix)] = obj
    fa, fb = {}, {}
    flatten([a["name"]], {"image_tiff_meta":a["image_tiff_meta"],"mask_tiff_meta":a["mask_tiff_meta"],"mask_stats":a["mask_stats"],"image_stats":a["image_stats"],"compat":a["compat"]}, fa)
    flatten([b["name"]], {"image_tiff_meta":b["image_tiff_meta"],"mask_tiff_meta":b["mask_tiff_meta"],"mask_stats":b["mask_stats"],"image_stats":b["image_stats"],"compat":b["compat"]}, fb)

    def strip_name_keys(d, name):
        out = {}
        for k,v in d.items():
            kk = k.replace(name+"/","")
            out[kk] = v
        return out

    fa2 = strip_name_keys(fa, a["name"])
    fb2 = strip_name_keys(fb, b["name"])

    keys = sorted(set(fa2.keys()) | set(fb2.keys()))
    rows = []
    for k in keys:
        va, vb = fa2.get(k, None), fb2.get(k, None)
        if (isinstance(va, float) and isinstance(vb, float) and (np.isnan(va) and np.isnan(vb))):
            continue
        if va != vb:
            rows.append({"field": k, "004": va, "404": vb})
    ddf = pd.DataFrame(rows)
    display(ddf)

    print("\nPER-PLANE IMAGE SUMMARY (first 128 planes):")
    def plane_summary(df):
        return {
            "n_planes": int(df.shape[0]),
            "constant_planes": int(df["is_constant"].sum()),
            "allzero_planes": int(df["is_all_zero"].sum()),
            "finite_frac_min": float(df["finite_frac"].min()),
            "finite_frac_mean": float(df["finite_frac"].mean()),
            "std_median": float(df["std"].median(skipna=True)),
            "std_min": float(df["std"].min(skipna=True)),
        }
    print("004:", plane_summary(a["image_plane_df"]))
    print("404:", plane_summary(b["image_plane_df"]))

    print("\nOUTDIR KEY FILES:")
    print("004 keyfiles:", a["outdir_summary"]["keyfiles_sample"][:20])
    print("404 keyfiles:", b["outdir_summary"]["keyfiles_sample"][:20])

# ---- RUN ----
case_004 = analyze_case(
    name="B004-A-004",
    image_path="/mnt/jwh83-data/Confetti/data/CODEX/new/done/B004-A-004.tif",
    mask_path="/mnt/jwh83-data/Confetti/output/intestine_data_mask_outputs/CellSAM_3_20260113_TIF/B004-A-004_rgb_cellSAM.tif",
    channel_csv="/mnt/jwh83-data/Confetti/data/CODEX/ns_mp_codex_channel_list.csv",
    outdir="/mnt/jwh83-data/Confetti/output/Redsea/20260127_ns444_CellSAM/B004-A-004",
)

case_404 = analyze_case(
    name="B004-A-404",
    image_path="/mnt/jwh83-data/Confetti/data/CODEX/new/done/B004-A-404.tif",
    mask_path="/mnt/jwh83-data/Confetti/output/intestine_data_mask_outputs/CellSAM_3_20260113_TIF/B004-A-404_rgb_cellSAM.tif",
    channel_csv="/mnt/jwh83-data/Confetti/data/CODEX/ns_mp_codex_channel_list.csv",
    outdir="/mnt/jwh83-data/Confetti/output/Redsea/20260127_ns444_CellSAM/B004-A-404",
)

show_case(case_004)
show_case(case_404)
diff_cases(case_004, case_404)

==================== B004-A-004 ====================

,path,exists,size_bytes,mtime,readable
0,/mnt/jwh83-data/Confetti/data/CODEX/new/done/B...,True,6166426287,2025-07-22 13:43:41,True
1,/mnt/jwh83-data/Confetti/output/intestine_data...,True,381160272,2026-01-27 15:09:39,True
2,/mnt/jwh83-data/Confetti/data/CODEX/ns_mp_code...,True,359,2025-10-13 15:40:09,True
3,/mnt/jwh83-data/Confetti/output/Redsea/2026012...,True,0,2026-01-27 18:12:19,True

TIFF META (image):
{
  "path": "/mnt/jwh83-data/Confetti/data/CODEX/new/done/B004-A-004.tif",
  "ok": true,
  "n_pages": 59,
  "is_ome": true,
  "series_count": 1,
  "series0_shape": [
    59,
    9529,
    10000
  ],
  "series0_dtype": "uint16",
  "series0_axes": "CYX",
  "page0_shape": [
    9529,
    10000
  ],
  "page0_dtype": "uint16",
  "page0_compression": "COMPRESSION.ADOBE_DEFLATE",
  "page0_photometric": "PHOTOMETRIC.MINISBLACK",
  "page0_planarconfig": "PLANARCONFIG.CONTIG",
  "page0_is_tiled": true,
  "page0_tilewidth": 512,
  "page0_tilelength": 512,
  "ome_metadata_present": true
}

TIFF META (mask):
{
  "path": "/mnt/jwh83-data/Confetti/output/intestine_data_mask_outputs/CellSAM_3_20260113_TIF/B004-A-004_rgb_cellSAM.tif",
  "ok": true,
  "n_pages": 1,
  "is_ome": false,
  "series_count": 1,
  "series0_shape": [
    9529,
    10000
  ],
  "series0_dtype": "int32",
  "series0_axes": "YX",
  "page0_shape": [
    9529,
    10000
  ],
  "page0_dtype": "int32",
  "page0_compression": "COMPRESSION.NONE",
  "page0_photometric": "PHOTOMETRIC.MINISBLACK",
  "page0_planarconfig": "1",
  "page0_is_tiled": false,
  "page0_rowsperstrip": 9529,
  "ome_metadata_present": false
}

MASK STATS:
{
  "shape": [
    9529,
    10000
  ],
  "dtype": "int32",
  "min": 0,
  "max": 126713,
  "unique_incl_0": 26895,
  "labels_excl_0": 26894,
  "centroid_rows": 26894,
  "label_min": 32,
  "label_max": 126713,
  "nonzero_pixels": 10152936,
  "has_negative": false,
  "has_non_integer": false,
  "contiguous_1_to_n": false,
  "missing_in_1_to_max": 99819,
  "tiny_n": 25,
  "tiny_labels_head": [
    18689,
    22172,
    44972,
    50887,
    51739,
    52961,
    54062,
    59477,
    70279,
    70986,
    76400,
    78292,
    82153,
    82313,
    82777,
    84555,
    89252,
    92718,
    92720,
    94369,
    96777,
    101622,
    107768,
    116496,
    121852
  ],
  "border_touch_n": 15,
  "border_touch_labels_head": [
    169,
    176,
    368,
    448,
    450,
    461,
    551,
    2440,
    2441,
    5202,
    5205,
    11120,
    13904,
    28908,
    55561
  ],
  "multi_component_smallest_n": 10,
  "multi_component_examples": [
    [
      51739,
      2
    ],
    [
      116496,
      2
    ],
    [
      70279,
      2
    ],
    [
      76400,
      4
    ],
    [
      92720,
      2
    ],
    [
      71311,
      7
    ],
    [
      70984,
      5
    ],
    [
      83608,
      5
    ],
    [
      78257,
      2
    ],
    [
      100889,
      7
    ]
  ],
  "area_summary": {
    "p0": 1.0,
    "p1": 60.0,
    "p5": 111.0,
    "p50": 341.0,
    "p95": 759.0,
    "p99": 1124.2099999999991,
    "max": 8462.0,
    "mean": 377.51676953967427
  },
  "labels_set_sample": [
    32,
    33,
    34,
    37,
    38,
    39,
    40,
    42,
    44,
    46,
    125903,
    125905,
    125908,
    125967,
    126045,
    126152,
    126191,
    126192,
    126710,
    126713
  ]
}

IMAGE STATS:
{
  "shape": [
    59,
    9529,
    10000
  ],
  "dtype": "uint16",
  "planes_inferred": 59,
  "yx": [
    9529,
    10000
  ],
  "sampling_step": 6,
  "nan_n_sample": 0,
  "inf_n_sample": 0,
  "any_nan_sample": false,
  "any_inf_sample": false,
  "constant_planes_n_first128": 0,
  "allzero_planes_n_first128": 0
}

IMAGE↔MASK COMPAT:
{
  "image_yx": [
    9529,
    10000
  ],
  "mask_yx": [
    9529,
    10000
  ],
  "same_xy": true,
  "delta_y": 0,
  "delta_x": 0
}

CHANNEL LIST:
{'path': '/mnt/jwh83-data/Confetti/data/CODEX/ns_mp_codex_channel_list.csv', 'rows': 59, 'cols': 1}

  marker_name
0    Hoechst1
1        MUC2
2        SOX9
3        MUC6
4        MUC1
5       GATA3
6        CD31
7     Synapto
8       Lefty
9       CD49f

OUTDIR SUMMARY:
{
  "outdir": "/mnt/jwh83-data/Confetti/output/Redsea/20260127_ns444_CellSAM/B004-A-004",
  "n_files": 2,
  "ext_counts": {
    ".csv": 2
  },
  "total_bytes": 33853661,
  "keyfiles_sample": [
    "/mnt/jwh83-data/Confetti/output/Redsea/20260127_ns444_CellSAM/B004-A-004/single_cell_after_redsea.csv",
    "/mnt/jwh83-data/Confetti/output/Redsea/20260127_ns444_CellSAM/B004-A-004/single_cell_before_redsea.csv"
  ],
  "all_files_sample": [
    "/mnt/jwh83-data/Confetti/output/Redsea/20260127_ns444_CellSAM/B004-A-004/single_cell_after_redsea.csv",
    "/mnt/jwh83-data/Confetti/output/Redsea/20260127_ns444_CellSAM/B004-A-004/single_cell_before_redsea.csv"
  ]
}

==================== B004-A-404 ====================

,path,exists,size_bytes,mtime,readable
0,/mnt/jwh83-data/Confetti/data/CODEX/new/done/B...,True,6359963418,2025-07-22 13:40:09,True
1,/mnt/jwh83-data/Confetti/output/intestine_data...,True,381158384,2026-01-27 15:10:13,True
2,/mnt/jwh83-data/Confetti/data/CODEX/ns_mp_code...,True,359,2025-10-13 15:40:09,True
3,/mnt/jwh83-data/Confetti/output/Redsea/2026012...,True,0,2026-01-27 15:12:46,True

TIFF META (image):
{
  "path": "/mnt/jwh83-data/Confetti/data/CODEX/new/done/B004-A-404.tif",
  "ok": true,
  "n_pages": 59,
  "is_ome": true,
  "series_count": 1,
  "series0_shape": [
    59,
    9528,
    10001
  ],
  "series0_dtype": "uint16",
  "series0_axes": "CYX",
  "page0_shape": [
    9528,
    10001
  ],
  "page0_dtype": "uint16",
  "page0_compression": "COMPRESSION.ADOBE_DEFLATE",
  "page0_photometric": "PHOTOMETRIC.MINISBLACK",
  "page0_planarconfig": "PLANARCONFIG.CONTIG",
  "page0_is_tiled": true,
  "page0_tilewidth": 512,
  "page0_tilelength": 512,
  "ome_metadata_present": true
}

TIFF META (mask):
{
  "path": "/mnt/jwh83-data/Confetti/output/intestine_data_mask_outputs/CellSAM_3_20260113_TIF/B004-A-404_rgb_cellSAM.tif",
  "ok": true,
  "n_pages": 1,
  "is_ome": false,
  "series_count": 1,
  "series0_shape": [
    9528,
    10001
  ],
  "series0_dtype": "int32",
  "series0_axes": "YX",
  "page0_shape": [
    9528,
    10001
  ],
  "page0_dtype": "int32",
  "page0_compression": "COMPRESSION.NONE",
  "page0_photometric": "PHOTOMETRIC.MINISBLACK",
  "page0_planarconfig": "1",
  "page0_is_tiled": false,
  "page0_rowsperstrip": 9528,
  "ome_metadata_present": false
}

MASK STATS:
{
  "shape": [
    9528,
    10001
  ],
  "dtype": "int32",
  "min": 0,
  "max": 183051,
  "unique_incl_0": 39299,
  "labels_excl_0": 39298,
  "centroid_rows": 39298,
  "label_min": 37,
  "label_max": 183051,
  "nonzero_pixels": 13045678,
  "has_negative": false,
  "has_non_integer": false,
  "contiguous_1_to_n": false,
  "missing_in_1_to_max": 143753,
  "tiny_n": 45,
  "tiny_labels_head": [
    37,
    5083,
    5095,
    5808,
    5917,
    6180,
    17069,
    21544,
    24669,
    28116,
    34484,
    41015,
    52481,
    55139,
    63951,
    70388,
    70392,
    74106,
    76168,
    78385,
    85076,
    87016,
    120734,
    128640,
    129215,
    135435,
    141938,
    142202,
    146048,
    146602
  ],
  "border_touch_n": 24,
  "border_touch_labels_head": [
    37,
    826,
    4570,
    4675,
    4812,
    5083,
    5095,
    5790,
    5808,
    5917,
    6180,
    6379,
    6772,
    179353,
    179423,
    179510,
    179652,
    179655,
    179657,
    180050,
    180056,
    180148,
    180361,
    180418
  ],
  "multi_component_smallest_n": 11,
  "multi_component_examples": [
    [
      76168,
      2
    ],
    [
      157462,
      2
    ],
    [
      120734,
      3
    ],
    [
      146602,
      2
    ],
    [
      146048,
      3
    ],
    [
      129215,
      5
    ],
    [
      17069,
      3
    ],
    [
      28116,
      8
    ],
    [
      70388,
      4
    ],
    [
      164202,
      8
    ],
    [
      21770,
      5
    ]
  ],
  "area_summary": {
    "p0": 1.0,
    "p1": 56.0,
    "p5": 104.0,
    "p50": 300.0,
    "p95": 661.0,
    "p99": 994.0,
    "max": 6378.0,
    "mean": 331.96798819278337
  },
  "labels_set_sample": [
    37,
    66,
    67,
    68,
    69,
    70,
    71,
    72,
    73,
    74,
    180612,
    180668,
    180669,
    180670,
    181122,
    182056,
    182979,
    182985,
    182987,
    183051
  ]
}

IMAGE STATS:
{
  "shape": [
    59,
    9528,
    10001
  ],
  "dtype": "uint16",
  "planes_inferred": 59,
  "yx": [
    9528,
    10001
  ],
  "sampling_step": 6,
  "nan_n_sample": 0,
  "inf_n_sample": 0,
  "any_nan_sample": false,
  "any_inf_sample": false,
  "constant_planes_n_first128": 0,
  "allzero_planes_n_first128": 0
}

IMAGE↔MASK COMPAT:
{
  "image_yx": [
    9528,
    10001
  ],
  "mask_yx": [
    9528,
    10001
  ],
  "same_xy": true,
  "delta_y": 0,
  "delta_x": 0
}

CHANNEL LIST:
{'path': '/mnt/jwh83-data/Confetti/data/CODEX/ns_mp_codex_channel_list.csv', 'rows': 59, 'cols': 1}

  marker_name
0    Hoechst1
1        MUC2
2        SOX9
3        MUC6
4        MUC1
5       GATA3
6        CD31
7     Synapto
8       Lefty
9       CD49f

OUTDIR SUMMARY:
{
  "outdir": "/mnt/jwh83-data/Confetti/output/Redsea/20260127_ns444_CellSAM/B004-A-404",
  "n_files": 0,
  "ext_counts": {},
  "total_bytes": 0,
  "keyfiles_sample": [],
  "all_files_sample": []
}

,field,004,404
0,compat/image_yx,"(9529, 10000)","(9528, 10001)"
1,compat/mask_yx,"(9529, 10000)","(9528, 10001)"
2,image_stats/shape,"(59, 9529, 10000)","(59, 9528, 10001)"
3,image_stats/yx,"(9529, 10000)","(9528, 10001)"
4,image_tiff_meta/page0_shape,"(9529, 10000)","(9528, 10001)"
5,image_tiff_meta/path,/mnt/jwh83-data/Confetti/data/CODEX/new/done/B...,/mnt/jwh83-data/Confetti/data/CODEX/new/done/B...
6,image_tiff_meta/series0_shape,"(59, 9529, 10000)","(59, 9528, 10001)"
7,mask_stats/area_summary/max,8462.0,6378.0
8,mask_stats/area_summary/mean,377.51677,331.967988
9,mask_stats/area_summary/p1,60.0,56.0
10,mask_stats/area_summary/p5,111.0,104.0
11,mask_stats/area_summary/p50,341.0,300.0
12,mask_stats/area_summary/p95,759.0,661.0
13,mask_stats/area_summary/p99,1124.21,994.0
14,mask_stats/border_touch_labels_head,"[169, 176, 368, 448, 450, 461, 551, 2440, 2441...","[37, 826, 4570, 4675, 4812, 5083, 5095, 5790, ..."
15,mask_stats/border_touch_n,15,24
16,mask_stats/centroid_rows,26894,39298
17,mask_stats/label_max,126713,183051
18,mask_stats/label_min,32,37
19,mask_stats/labels_excl_0,26894,39298
20,mask_stats/labels_set_sample,"[32, 33, 34, 37, 38, 39, 40, 42, 44, 46, 12590...","[37, 66, 67, 68, 69, 70, 71, 72, 73, 74, 18061..."
21,mask_stats/max,126713,183051
22,mask_stats/missing_in_1_to_max,99819,143753
23,mask_stats/multi_component_examples,<list len=10>,<list len=11>
24,mask_stats/multi_component_smallest_n,10,11
25,mask_stats/nonzero_pixels,10152936,13045678
26,mask_stats/shape,"(9529, 10000)","(9528, 10001)"
27,mask_stats/tiny_labels_head,"[18689, 22172, 44972, 50887, 51739, 52961, 540...","[37, 5083, 5095, 5808, 5917, 6180, 17069, 2154..."
28,mask_stats/tiny_n,25,45
29,mask_stats/unique_incl_0,26895,39299
30,mask_tiff_meta/page0_rowsperstrip,9529,9528
31,mask_tiff_meta/page0_shape,"(9529, 10000)","(9528, 10001)"
32,mask_tiff_meta/path,/mnt/jwh83-data/Confetti/output/intestine_data...,/mnt/jwh83-data/Confetti/output/intestine_data...
33,mask_tiff_meta/series0_shape,"(9529, 10000)","(9528, 10001)"

PER-PLANE IMAGE SUMMARY (first 128 planes):
004: {'n_planes': 59, 'constant_planes': 0, 'allzero_planes': 0, 'finite_frac_min': 1.0, 'finite_frac_mean': 1.0, 'std_median': 566.5761108398438, 'std_min': 26.284643173217773}
404: {'n_planes': 59, 'constant_planes': 0, 'allzero_planes': 0, 'finite_frac_min': 1.0, 'finite_frac_mean': 1.0, 'std_median': 742.0722045898438, 'std_min': 132.688232421875}

OUTDIR KEY FILES:
004 keyfiles: ['/mnt/jwh83-data/Confetti/output/Redsea/20260127_ns444_CellSAM/B004-A-004/single_cell_after_redsea.csv', '/mnt/jwh83-data/Confetti/output/Redsea/20260127_ns444_CellSAM/B004-A-004/single_cell_before_redsea.csv']
404 keyfiles: []

In [1]:
import os, sys, time, subprocess, textwrap, json, glob
import numpy as np
import pandas as pd

try:
    import tifffile as tiff
except Exception:
    tiff = None

from skimage.measure import regionprops_table


IMG = "/mnt/jwh83-data/Confetti/data/CODEX/new/done/B004-A-404.tif"
MASK = "/mnt/jwh83-data/Confetti/output/intestine_data_mask_outputs/CellSAM_3_20260113_TIF/B004-A-404_rgb_cellSAM.tif"
CH = "/mnt/jwh83-data/Confetti/data/CODEX/ns_mp_codex_channel_list.csv"
OUTDIR = "/mnt/jwh83-data/Confetti/output/Redsea/20260127_ns444_CellSAM/B004-A-404"
ELEMENT_SHAPE = "star"
ELEMENT_SIZE = "2"


def stat_path(p):
    d = {"path": p, "exists": os.path.exists(p)}
    if d["exists"]:
        st = os.stat(p)
        d.update(size_bytes=int(st.st_size), mtime=time.strftime("%Y-%m-%d %H:%M:%S", time.localtime(st.st_mtime)))
    return d

def list_files(root, maxn=2000):
    if not os.path.exists(root):
        return []
    out = []
    for p in glob.glob(os.path.join(root, "**/*"), recursive=True):
        if os.path.isfile(p):
            out.append(p)
        if len(out) >= maxn:
            break
    return sorted(out)

def summarize_outdir(root):
    files = list_files(root)
    ext_counts = pd.Series([os.path.splitext(f)[1].lower() for f in files]).value_counts().to_dict() if files else {}
    sizes = []
    for f in files:
        try:
            sizes.append(os.stat(f).st_size)
        except Exception:
            pass
    key = [f for f in files if any(k in os.path.basename(f).lower() for k in ["before","after","single","cell","log","trace","error"])]
    return {
        "exists": os.path.exists(root),
        "n_files": len(files),
        "ext_counts": ext_counts,
        "total_bytes": int(sum(sizes)) if sizes else 0,
        "keyfiles_head": key[:30],
        "files_head": files[:30],
    }

def read_mask(mask_path):
    if tiff is None:
        raise ImportError("tifffile not installed")
    m = tiff.imread(mask_path)
    if m.ndim == 3 and m.shape[-1] in (3,4):
        raise ValueError(f"Mask looks RGB/RGBA: {m.shape}")
    return m

def mask_diagnostics(mask_path, small_area=10):
    m = read_mask(mask_path).astype(np.int64, copy=False)
    uniq = np.unique(m)
    labels = uniq[uniq != 0]
    props = regionprops_table(m, properties=("label","area","bbox","centroid"))
    df = pd.DataFrame(props).rename(columns={"centroid-0":"y_centroid","centroid-1":"x_centroid"}).sort_values("label")
    tiny = df[df["area"] < small_area]
    h,w = m.shape[:2]
    border = df[(df["bbox-0"]==0)|(df["bbox-1"]==0)|(df["bbox-2"]==h)|(df["bbox-3"]==w)]
    return {
        "mask_shape": tuple(m.shape),
        "mask_dtype": str(m.dtype),
        "unique_incl_0": int(uniq.size),
        "labels_excl_0": int(labels.size),
        "label_min": int(df["label"].min()) if len(df) else None,
        "label_max": int(df["label"].max()) if len(df) else None,
        "centroid_rows": int(len(df)),
        "nonzero_pixels": int(np.count_nonzero(m)),
        "tiny_n_area_lt_10": int(len(tiny)),
        "tiny_labels_head": tiny["label"].head(20).astype(int).tolist(),
        "border_touch_n": int(len(border)),
        "border_touch_labels_head": border["label"].head(20).astype(int).tolist(),
        "area_quantiles": {
            "p1": float(np.quantile(df["area"], 0.01)) if len(df) else None,
            "p5": float(np.quantile(df["area"], 0.05)) if len(df) else None,
            "p50": float(np.quantile(df["area"], 0.50)) if len(df) else None,
            "p95": float(np.quantile(df["area"], 0.95)) if len(df) else None,
            "p99": float(np.quantile(df["area"], 0.99)) if len(df) else None,
        } if len(df) else {},
    }

def image_tiff_meta(path):
    if tiff is None:
        return {"ok": False, "error": "tifffile not installed"}
    if not os.path.exists(path):
        return {"ok": False, "error": "missing"}
    try:
        with tiff.TiffFile(path) as tf:
            s0 = tf.series[0]
            p0 = tf.pages[0]
            return {
                "ok": True,
                "is_ome": bool(tf.is_ome),
                "series_count": len(tf.series),
                "series0_shape": tuple(s0.shape),
                "series0_axes": getattr(s0, "axes", None),
                "series0_dtype": str(s0.dtype),
                "n_pages": len(tf.pages),
                "page0_shape": tuple(getattr(p0, "shape", ())),
                "page0_dtype": str(getattr(p0, "dtype", "")),
                "page0_compression": str(getattr(p0, "compression", "")),
                "page0_is_tiled": bool(getattr(p0, "is_tiled", False)),
            }
    except Exception as e:
        return {"ok": False, "error": repr(e)}

def run_redsea_with_diagnostics():
    os.makedirs(OUTDIR, exist_ok=True)
    diag_dir = os.path.join(OUTDIR, "_diagnostics")
    os.makedirs(diag_dir, exist_ok=True)
    log_path = os.path.join(diag_dir, "redsea_stdout_stderr.log")
    meta_path = os.path.join(diag_dir, "preflight_meta.json")

    pre = {
        "python": sys.version,
        "executable": sys.executable,
        "cwd": os.getcwd(),
        "argv_example": "redsea ...",
        "inputs": {
            "image": stat_path(IMG),
            "mask": stat_path(MASK),
            "channels": stat_path(CH),
            "outdir": stat_path(OUTDIR),
        },
        "image_tiff_meta": image_tiff_meta(IMG),
        "mask_tiff_meta": image_tiff_meta(MASK),
        "mask_diagnostics": None,
        "outdir_before": summarize_outdir(OUTDIR),
    }

    try:
        pre["mask_diagnostics"] = mask_diagnostics(MASK)
    except Exception as e:
        pre["mask_diagnostics_error"] = repr(e)

    try:
        import redseapy
        pre["redseapy_version"] = getattr(redseapy, "__version__", "unknown")
    except Exception as e:
        pre["redseapy_import_error"] = repr(e)

    with open(meta_path, "w") as f:
        json.dump(pre, f, indent=2)

    cmd = [
        "redsea",
        IMG,
        MASK,
        CH,
        OUTDIR,
        "--element-shape", ELEMENT_SHAPE,
        "--element-size", str(ELEMENT_SIZE),
    ]

    print("=== PRE-FLIGHT ===")
    print("Command:\n", " ".join(cmd))
    print("\nInputs:")
    print(json.dumps(pre["inputs"], indent=2))
    print("\nImage TIFF meta:")
    print(json.dumps(pre["image_tiff_meta"], indent=2)[:1200])
    print("\nMask TIFF meta:")
    print(json.dumps(pre["mask_tiff_meta"], indent=2)[:1200])
    if pre.get("mask_diagnostics") is not None:
        print("\nMask diagnostics:")
        print(json.dumps(pre["mask_diagnostics"], indent=2)[:2000])
    print("\nOutdir before:")
    print(json.dumps(pre["outdir_before"], indent=2)[:2000])

    print(f"\nLogging stdout+stderr to: {log_path}")
    t0 = time.time()
    proc = subprocess.run(cmd, capture_output=True, text=True)
    dt = time.time() - t0

    with open(log_path, "w") as f:
        f.write(proc.stdout or "")
        if proc.stderr:
            f.write("\n\n===== STDERR =====\n\n")
            f.write(proc.stderr)

    print("\n=== RUN RESULT ===")
    print("returncode:", proc.returncode)
    print("elapsed_sec:", round(dt, 2))

    out_after = summarize_outdir(OUTDIR)
    with open(os.path.join(diag_dir, "outdir_after.json"), "w") as f:
        json.dump(out_after, f, indent=2)

    print("\nOutdir after:")
    print(json.dumps(out_after, indent=2)[:2000])

    if proc.returncode != 0:
        combined = (proc.stdout or "") + "\n" + (proc.stderr or "")
        lines = combined.splitlines()

        tb_idx = [i for i,l in enumerate(lines) if "Traceback (most recent call last)" in l]
        if tb_idx:
            i0 = tb_idx[-1]
            excerpt = "\n".join(lines[i0:i0+80])
            print("\n=== TRACEBACK (excerpt) ===")
            print(excerpt)
        else:
            print("\n(No Python traceback detected; see log file.)")

        valerr = [l for l in lines if "ValueError:" in l][-5:]
        if valerr:
            print("\n=== ValueError lines ===")
            for l in valerr:
                print(l)

        print("\nOpen the log file for full details:")
        print(log_path)

    return proc.returncode, log_path, meta_path, diag_dir

run_redsea_with_diagnostics()

=== PRE-FLIGHT ===
Command:
 redsea /mnt/jwh83-data/Confetti/data/CODEX/new/done/B004-A-404.tif /mnt/jwh83-data/Confetti/output/intestine_data_mask_outputs/CellSAM_3_20260113_TIF/B004-A-404_rgb_cellSAM.tif /mnt/jwh83-data/Confetti/data/CODEX/ns_mp_codex_channel_list.csv /mnt/jwh83-data/Confetti/output/Redsea/20260127_ns444_CellSAM/B004-A-404 --element-shape star --element-size 2

Inputs:
{
  "image": {
    "path": "/mnt/jwh83-data/Confetti/data/CODEX/new/done/B004-A-404.tif",
    "exists": true,
    "size_bytes": 6359963418,
    "mtime": "2025-07-22 13:40:09"
  },
  "mask": {
    "path": "/mnt/jwh83-data/Confetti/output/intestine_data_mask_outputs/CellSAM_3_20260113_TIF/B004-A-404_rgb_cellSAM.tif",
    "exists": true,
    "size_bytes": 381158384,
    "mtime": "2026-01-27 15:10:13"
  },
  "channels": {
    "path": "/mnt/jwh83-data/Confetti/data/CODEX/ns_mp_codex_channel_list.csv",
    "exists": true,
    "size_bytes": 359,
    "mtime": "2025-10-13 15:40:09"
  },
  "outdir": {
    "path": "/mnt/jwh83-data/Confetti/output/Redsea/20260127_ns444_CellSAM/B004-A-404",
    "exists": true,
    "size_bytes": 0,
    "mtime": "2026-02-13 17:46:24"
  }
}

Image TIFF meta:
{
  "ok": true,
  "is_ome": true,
  "series_count": 1,
  "series0_shape": [
    59,
    9528,
    10001
  ],
  "series0_axes": "CYX",
  "series0_dtype": "uint16",
  "n_pages": 59,
  "page0_shape": [
    9528,
    10001
  ],
  "page0_dtype": "uint16",
  "page0_compression": "COMPRESSION.ADOBE_DEFLATE",
  "page0_is_tiled": true
}

Mask TIFF meta:
{
  "ok": true,
  "is_ome": false,
  "series_count": 1,
  "series0_shape": [
    9528,
    10001
  ],
  "series0_axes": "YX",
  "series0_dtype": "int32",
  "n_pages": 1,
  "page0_shape": [
    9528,
    10001
  ],
  "page0_dtype": "int32",
  "page0_compression": "COMPRESSION.NONE",
  "page0_is_tiled": false
}

Mask diagnostics:
{
  "mask_shape": [
    9528,
    10001
  ],
  "mask_dtype": "int64",
  "unique_incl_0": 39299,
  "labels_excl_0": 39298,
  "label_min": 37,
  "label_max": 183051,
  "centroid_rows": 39298,
  "nonzero_pixels": 13045678,
  "tiny_n_area_lt_10": 45,
  "tiny_labels_head": [
    37,
    5083,
    5095,
    5808,
    5917,
    6180,
    17069,
    21544,
    24669,
    28116,
    34484,
    41015,
    52481,
    55139,
    63951,
    70388,
    70392,
    74106,
    76168,
    78385
  ],
  "border_touch_n": 24,
  "border_touch_labels_head": [
    37,
    826,
    4570,
    4675,
    4812,
    5083,
    5095,
    5790,
    5808,
    5917,
    6180,
    6379,
    6772,
    179353,
    179423,
    179510,
    179652,
    179655,
    179657,
    180050
  ],
  "area_quantiles": {
    "p1": 56.0,
    "p5": 104.0,
    "p50": 300.0,
    "p95": 661.0,
    "p99": 994.0
  }
}

Outdir before:
{
  "exists": true,
  "n_files": 0,
  "ext_counts": {},
  "total_bytes": 0,
  "keyfiles_head": [],
  "files_head": []
}

Logging stdout+stderr to: /mnt/jwh83-data/Confetti/output/Redsea/20260127_ns444_CellSAM/B004-A-404/_diagnostics/redsea_stdout_stderr.log

=== RUN RESULT ===
returncode: 1
elapsed_sec: 8150.57

Outdir after:
{
  "exists": true,
  "n_files": 2,
  "ext_counts": {
    ".json": 1,
    ".log": 1
  },
  "total_bytes": 3825921,
  "keyfiles_head": [
    "/mnt/jwh83-data/Confetti/output/Redsea/20260127_ns444_CellSAM/B004-A-404/_diagnostics/redsea_stdout_stderr.log"
  ],
  "files_head": [
    "/mnt/jwh83-data/Confetti/output/Redsea/20260127_ns444_CellSAM/B004-A-404/_diagnostics/preflight_meta.json",
    "/mnt/jwh83-data/Confetti/output/Redsea/20260127_ns444_CellSAM/B004-A-404/_diagnostics/redsea_stdout_stderr.log"
  ]
}

=== TRACEBACK (excerpt) ===
Traceback (most recent call last):
  File "/home/labuser/anaconda3/envs/redseapy/bin/redsea", line 7, in <module>
    sys.exit(redsea())
  File "/home/labuser/anaconda3/envs/redseapy/lib/python3.10/site-packages/redseapy/cli.py", line 66, in redsea
    redsea_mod.run_redsea(
  File "/home/labuser/anaconda3/envs/redseapy/lib/python3.10/site-packages/redseapy/redsea.py", line 363, in run_redsea
    d["x_centroid"] = centroid_xs
  File "/home/labuser/anaconda3/envs/redseapy/lib/python3.10/site-packages/pandas/core/frame.py", line 4322, in __setitem__
    self._set_item(key, value)
  File "/home/labuser/anaconda3/envs/redseapy/lib/python3.10/site-packages/pandas/core/frame.py", line 4535, in _set_item
    value, refs = self._sanitize_column(value)
  File "/home/labuser/anaconda3/envs/redseapy/lib/python3.10/site-packages/pandas/core/frame.py", line 5288, in _sanitize_column
    com.require_length_match(value, self.index)
  File "/home/labuser/anaconda3/envs/redseapy/lib/python3.10/site-packages/pandas/core/common.py", line 573, in require_length_match
    raise ValueError(
ValueError: Length of values (29876) does not match length of index (29873)

=== ValueError lines ===
ValueError: Length of values (29876) does not match length of index (29873)

Open the log file for full details:
/mnt/jwh83-data/Confetti/output/Redsea/20260127_ns444_CellSAM/B004-A-404/_diagnostics/redsea_stdout_stderr.log

(1,
 '/mnt/jwh83-data/Confetti/output/Redsea/20260127_ns444_CellSAM/B004-A-404/_diagnostics/redsea_stdout_stderr.log',
 '/mnt/jwh83-data/Confetti/output/Redsea/20260127_ns444_CellSAM/B004-A-404/_diagnostics/preflight_meta.json',
 '/mnt/jwh83-data/Confetti/output/Redsea/20260127_ns444_CellSAM/B004-A-404/_diagnostics')